### ISSUE TITLE
Failed installation shoehorn 2.8.1.1 

### ISSUE THREAD

**Issue by tomas023** [gjb2048/moodle-theme_shoehorn#10]
After my attempt to install version 2.8.1.1 shoehorn white screen appeared, and it was impossible to get into the admin interface Moodle 2.8.5+ (Bootstrap theme 2015043000). I installed Moodle 2.8.5+ again but the same problem appeared after trying to install version 2.8.1.1 Shoehorn.

**Comment by gjb2048** [comment]
Thanks for the report.

Literately a few hours ago I discovered that this line: https://github.com/gjb2048/moodle-theme_shoehorn/blob/12dd69455b43f78f9fcb1d1bc63b737b35389a19/layout/maintenance.php#L38 - should be 'shoehorn_grid' instead of 'bootstrap_grid'.  Please change and let me know if it fixes it for you.

To get Moodle back, in the DB, table 'config' change the row with the attribute name of 'theme' with the value field set to 'clean' and then run a command line purge all caches -> https://docs.moodle.org/28/en/Administration_via_command_line#Purge_caches

**Comment by tomas023** [comment]
Thank you, it works well now... :-)

**Comment by gjb2048** [comment]
Thanks for letting me know, I'll release V2.8.1.2 hopefully tomorrow with the fix.

**Comment by gjb2048** [comment]
Fixed in M2.8 and M2.9: https://moodle.org/mod/forum/discuss.php?d=313037
